
@baseUrl = http://127.0.0.1:5000
@symbol = BNBUSDT

###

# @name getLatestCandle
GET {{baseUrl}}/market/candles/{{symbol}}

###

# @name adaptiveStrategyId
POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "{{symbol}}",
    "entry": "{{getLatestCandle.response.body.candles[0].close_price}}",
    "quantity": "0.1",
    "TP1": "{{getLatestCandle.response.body.candles[0].high_price}}",
    "SL1": "{{getLatestCandle.response.body.candles[0].low_price}}"
}

###

# Changes stategy status to stop
PUT  {{baseUrl}}{{adaptiveStrategyId.response.headers.location}}/status
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}
Content-Type: application/json

{
    "status": "STOPPED"
}

###

#  Retrieves strategy status
GET  {{baseUrl}}{{adaptiveStrategyId.response.headers.location}}/status
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

###

# Retrieve the object created by the request above
GET {{baseUrl}}/strategy_advice/telegram/{{adaptiveStrategyId.response.body.strategy_id}}
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}