
@baseUrl = http://127.0.0.1:5000

###
# Long BTCUSDT

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "BTCUSDT",
    "entry": "32050.0",
    "quantity": "0.02",
    "TP1": "36050",
    "SL1": 29100
}

###
# Short BTCUSDT

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "BTCUSDT",
    "entry": "32050.0",
    "quantity": "0.02",
    "SL1": "36050",
    "TP1": 29100
}

###
# Bad request - missing mandatory fields

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "BTCUSDT", "SL1": "36050", "TP1": 29100 }


###
# Bad request - uses float

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "BTCUSDT", "SL1": "36050", "TP1": 29100.0 }



###

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSDT", "TP1": "1311.5", "SL1": 1112 }

###
# Unauthorized request, should fail with HTTP 401

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json

{ "symbol": "ETHUSDT", "TP1": "1311.5", "SL1": 1112 }


###
# Bad request: decimal conversion error

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSDT", "TP1": "13.11.5", "SL1": 1112 }

###
# Bad request: unknown currency

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSD", "TP1": "1311.5", "SL1": 1112 }

###

GET {{baseUrl}}/market/candles/BTCUSDT

###

GET {{baseUrl}}/market/candles/ETHUSDT

###
# Should fail since we're not listening to ETHUSD

GET {{baseUrl}}/market/candles/ETHUSD
