
@baseUrl = http://127.0.0.1:5000
@wrong_id = 200TT001

###
# Long BNBUSDT

# @name bnbUsdtStrategyId
POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "BNBUSDT",
    "entry": "200.0",
    "quantity": "0.02",
    "TP1": "220",
    "SL1": 195
}

###

# Changes stategy status to stop
PUT  {{baseUrl}}{{bnbUsdtStrategyId.response.headers.location}}/status
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}
Content-Type: application/json

{
    "status": "STOPPED"
}

###

# Sending a bad stategy status
PUT  {{baseUrl}}{{bnbUsdtStrategyId.response.headers.location}}/status
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}
Content-Type: application/json

{
    "status": "WRONG"
}

###

#  Retrieves strategy status
GET  {{baseUrl}}{{bnbUsdtStrategyId.response.headers.location}}/status
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}


###

# Retrieve the object created by the request above
GET {{baseUrl}}/strategy_advice/telegram/{{bnbUsdtStrategyId.response.body.strategy_id}}
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

###

# Try to retrieve the object created by the request using wrong strategy id
GET {{baseUrl}}/strategy_advice/telegram/{{wrong_id}}
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

###

# Retrieve the object created by the request using Location header value
GET {{baseUrl}}{{bnbUsdtStrategyId.response.headers.location}}
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

###
# Long BTCUSDT

# @name btcUsdtStrategyId
POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "BTCUSDT",
    "entry": "32050.0",
    "quantity": "0.02",
    "TP1": "36050",
    "SL1": 29100
}

###
# Short BTCUSDT

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{
    "symbol": "BTCUSDT",
    "entry": "32050.0",
    "quantity": "0.02",
    "SL1": "36050",
    "TP1": 29100
}

###
# Bad request - missing mandatory fields

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "BTCUSDT", "SL1": "36050", "TP1": 29100 }


###
# Bad request - uses float

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "BTCUSDT", "SL1": "36050", "TP1": 29100.0 }



###

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSDT", "TP1": "1311.5", "SL1": 1112 }

###
# Unauthorized request, should fail with HTTP 401

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json

{ "symbol": "ETHUSDT", "TP1": "1311.5", "SL1": 1112 }


###
# Bad request: decimal conversion error

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSDT", "TP1": "13.11.5", "SL1": 1112 }

###
# Bad request: unknown currency

POST {{baseUrl}}/strategy_advice/telegram/
Content-Type: application/json
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

{ "symbol": "ETHUSD", "TP1": "1311.5", "SL1": 1112 }

###

# List Strategies

GET {{baseUrl}}/strategy_advice/telegram/
Authorization: Basic telegram {{$dotenv TELEGRAM_USER_PASSWORD}}

###

GET {{baseUrl}}/market/candles/BTCUSDT

###

GET {{baseUrl}}/market/candles/ETHUSDT

###
# Should fail since we're not listening to ETHUSD

GET {{baseUrl}}/market/candles/ETHUSD

###
# Get system status

GET {{baseUrl}}/status
