[binance]
connection = "test"     # Valid values: test, live
# Put valid API key and API secret values for the configuration to work
api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
api_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# User accounts and their corresponding passwords
# in the form: user = "password"
[user_passwords]
telegram = "xxxxxxxxx"

[logging]
level = "INFO"
